kind: secret
name: username
get:
  path: caesar-team/data/registry
  name: username
---
kind: secret
name: password
get:
  path: caesar-team/data/registry
  name: password
---
kind: secret
name: repository
get:
  path: caesar-team/data/registry
  name: repo-security
---
kind: secret
name: registry
get:
  path: secret/data/registry
  name: registry
---
kind: secret
name: develop_url
get:
  path: secret/data/k8s-4xxi
  name: develop_url
---
kind: secret
name: develop_token
get:
  path: secret/data/k8s-4xxi
  name: develop_token
---
kind: secret
name: develop_ca
get:
  path: secret/data/k8s-4xxi
  name: develop_ca
---
kind: secret
name: master_url
get:
  path: secret/data/k8s-4xxi
  name: staging_url
---
kind: secret
name: master_token
get:
  path: secret/data/k8s-4xxi
  name: staging_token
---
kind: secret
name: master_ca
get:
  path: secret/data/k8s-4xxi
  name: staging_ca
---
kind: secret
name: notifications
get:
  path: secret/data/notifications-4xxi
  name: caesar-builds
---
kind: secret
name: notification_username
get:
  path: secret/data/notifications-4xxi
  name: username
---
kind: secret
name: notification_icon
get:
  path: secret/data/notifications-4xxi
  name: icon_url
---
kind: secret
name: ssh_key
get:
  path: secret/data/alfa-lk-ssh
  name: ssh-priv-base64
---
kind: pipeline
type: docker
name: 4xxis
globals:
- &confNoSaveBuild
  dockerfile: ./config/docker/php/Dockerfile
  repo: plugins/docker
  tag: fourxxi
  dry_run: true
  daemon_off: false

- &confSaveBuild
  dockerfile: ./config/docker/php/Dockerfile
  repo: 
    from_secret: repository
  tag: ${DRONE_BRANCH}
  username:
    from_secret: username
  password:
    from_secret: password

- &stepCheckBuild
  name: build test
  image: plugins/docker
  settings:
    <<: *confNoSaveBuild

- &stepMainBuild
  name: build
  image: plugins/docker
  settings:
    <<: *confSaveBuild

- &stepDevelopDeploy
  name: deploy develop
  image: sinlead/drone-kubectl
  settings:
    kubernetes_server:
      from_secret: develop_url
    kubernetes_token:
      from_secret: develop_token
    kubernetes_cert:
      from_secret: develop_ca
  environment:
    CICD_GIT_COMMIT: ${DRONE_COMMIT}
    CICD_GIT_BRANCH: ${DRONE_BRANCH}
  commands:
  - sed -i "s/\$CICD_GIT_BRANCH/$CICD_GIT_BRANCH/g" deploy/004_deployment.yml
  - sed -i "s/\$CICD_GIT_COMMIT/$CICD_GIT_COMMIT/g" deploy/004_deployment.yml
  - kubectl apply -f deploy/004_deployment.yml

- &stepMasterDeploy
  name: deploy staging
  image: sinlead/drone-kubectl
  settings:
    kubernetes_server:
      from_secret: master_url
    kubernetes_token: 
      from_secret: master_token
    kubernetes_cert: 
      from_secret: master_ca
  environment:
    CICD_GIT_COMMIT: ${DRONE_COMMIT}
    CICD_GIT_BRANCH: ${DRONE_BRANCH}
  commands:
  - sed -i "s/\$CICD_GIT_BRANCH/$CICD_GIT_BRANCH/g" deploy/004_deployment.yml
  - sed -i "s/\$CICD_GIT_COMMIT/$CICD_GIT_COMMIT/g" deploy/004_deployment.yml
  - kubectl apply -f deploy/004_deployment.yml

- &stepNotifyToSlack
  name: notify-to-slack
  image: plugins/slack
  pull: always
  settings:
    webhook:
      from_secret: notifications
    channel: caesar-builds
    username: 
      from_secret: notification_username
    icon_url:
      from_secret: notification_icon
    template: >
      {{#success build.status}}
       *Event*: `{{build.event}}` {{build.status}}
       *Repository*: `{{repo.name}}` to `{{build.branch}}`
       *Commit*: `{{build.commit}}`
       *Info*: {{build.number}} build was started {{since build.created}} and executed for {{since build.started}}
      <{{build.link}}|*Build link*>
      {{else}}
       *Event*: `{{build.event}}` {{build.status}}
       *Repository*: `{{repo.name}}` to `{{build.branch}}`
       *Commit*: `{{build.commit}}`
       *Info*: {{build.number}} build was started {{since build.created}} and executed for {{since build.started}}
      <{{build.link}}|*Build link*>
      {{/success}}
steps:
- <<: *stepCheckBuild
  when:
    branch: [ feature/* ]

- <<: *stepMainBuild
  when:
    branch: [ develop, master ]

- <<: *stepDevelopDeploy
  when:
    branch: [ develop ]

- <<: *stepMasterDeploy
  when:
    branch: [ master ]

- <<: *stepNotifyToSlack
  when:
    status: [ success, failure ]
    branch: [ develop, master ]

trigger:
  branch:
  - master
  - develop
  - feature/*
