http:
  address: ${RR_HTTP_ADDRESS}

  uploads:
    forbid: [".php", ".exe", ".bat"]

  workers:
    command: "php bin/console baldinof:roadrunner:worker"
    relay: "unix://var/roadrunner.sock"
    pool:
      numWorkers: ${RR_POOL_NUM_WORKERS}
      maxJobs:    ${RR_HTTP_MAX_JOBS}

static:
  dir:   "public"
  forbid: [".php", ".htaccess"]

limit:
  services:
    http:
      maxMemory: ${RR_HTTP_MAX_MEMORY}