version: '3.2'

services:
  php:
    build:
      context: .
      args:
        COMPOSER_AUTH: ${COMPOSER_AUTH}
    depends_on:
      - redis
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV
      - PHP_IDE_CONFIG
    expose:
      - "9000"
    ports:
      - 8080:8080
    entrypoint: ./docker-entrypoint.sh
    user: "$UID:$UID"
  redis:
    image: 'redis:5-alpine'
    environment:
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - "redis:/etc/redis/database/caesarapp"
    ports:
      - "${REDIS_PORT}:6379"
volumes:
  redis:
