version: '3.2'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        COMPOSER_AUTH: ${COMPOSER_AUTH}
    depends_on:
      - redis
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV
      - RR_HTTP_ADDRESS
      - RR_POOL_NUM_WORKERS
      - RR_HTTP_MAX_MEMORY
      - RR_HTTP_MAX_JOBS
    expose:
      - "9000"
    ports:
      - 8080:8080
    entrypoint: ./docker-entrypoint.sh
    user: "$UID:$UID"
  redis:
    image: 'redis:5-alpine'
    environment:
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - "redis:/etc/redis/database/caesarapp"
    ports:
      - "${REDIS_PORT}:6379"
volumes:
  redis:
