---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caesar-secure-message-server
  labels:
    app: caesar-secure-message-server
    CICD_GIT_COMMIT: ${CICD_GIT_COMMIT}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caesar-secure-message-server
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 25%
    type: RollingUpdate 
  template:
    metadata:
      labels:
        app: caesar-secure-message-server
        CICD_GIT_COMMIT: ${CICD_GIT_COMMIT}
    spec:
      containers:
      - name: caesar-secure-message-server
        image: "caesarteam/caesar-secure-message-server:${CICD_GIT_BRANCH}"
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: caesar-server-config
        - secretRef:
            name: caesar-server-secret
        - secretRef:
            name: postgres-secret
        - secretRef:
            name: rabbitmq-secret 
        - configMapRef:
            name: rabbitmq-config
        - configMapRef:
            name: redis-config
        - secretRef:
            name: mailer-secret
        - configMapRef:
            name: mailer-config        
        ports:
        - name: php-fpm
          containerPort: 9000 
        volumeMounts:
        - mountPath: /var/www/html/public
          name: caesar-secure-message
      - name: nginx
        image: "nginx:alpine"
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 0 
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-config-volume
          subPath: nginx.conf
        - mountPath: /var/www/html/public
          name: caesar-secure-message
      initContainers:
      - name: copy-public
        image: "caesarteam/caesar-secure-message-server:${CICD_GIT_BRANCH}"
        imagePullPolicy: IfNotPresent
        command: [ "/bin/cp", "-r", "public/.", "public_site/" ]
        volumeMounts:
        - mountPath: /var/www/html/public_site
          name: caesar-secure-message
      securityContext:
        runAsUser: 82
        runAsGroup: 82
        fsGroup: 82
      volumes:
      - name: caesar-secure-message
        persistentVolumeClaim:
          claimName: caesar-secure-message
      - configMap:
          defaultMode: 256
          name: nginx-config
          optional: false
        name: nginx-config-volume