apiVersion: apps/v1
kind: Deployment
metadata:
  name: caesar-secure-message-server
  namespace: caesar-secure-message
  labels:
    app: caesar-secure-message-server
    CICD_GIT_COMMIT: $CICD_GIT_COMMIT
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caesar-secure-message-server
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 25%
    type: RollingUpdate 
  template:
    metadata:
      namespace: caesar-secure-message
      labels:
        app: caesar-secure-message-server
        CICD_GIT_COMMIT: $CICD_GIT_COMMIT
    spec:
      containers:
      - name: caesar-secure-message-server
        image: "caesarteam/caesar-secure-message-server:$CICD_GIT_BRANCH"
        imagePullPolicy: Always
        command:
        - bin/rr
        - serve
        - --debug
        - -vvv
        envFrom:
        - configMapRef:
            name: caesar-server-config
        - secretRef:
            name: caesar-server-secret
        - configMapRef:
            name: redis-config
        - secretRef:
            name: caesar-secure-message-server-secrets   
        ports:
        - name: roadrunner
          containerPort: 8080 
      securityContext:
        runAsUser: 82
        runAsGroup: 82
        fsGroup: 82
